# Generated by Django 5.2.10 on 2026-01-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0005_alter_barschedule_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barschedule',
            options={'ordering': ['start_day'], 'verbose_name': 'Horário de Funcionamento', 'verbose_name_plural': 'Horários de Funcionamento'},
        ),
        migrations.RemoveField(
            model_name='barschedule',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='barschedule',
            name='is_open',
        ),
        migrations.AddField(
            model_name='barschedule',
            name='end_day',
            field=models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], default=4, help_text='Dia de fim'),
        ),
        migrations.AddField(
            model_name='barschedule',
            name='start_day',
            field=models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], default=4, help_text='Dia de início'),
            preserve_default=False,
        ),
    ]
