# Generated by Django 5.2.10 on 2026-01-31 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0004_barschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barschedule',
            options={'ordering': ['day_of_week'], 'verbose_name': 'Horário de Funcionamento', 'verbose_name_plural': 'Horários de Funcionamento'},
        ),
    ]
