# Generated by Django 5.2.10 on 2026-02-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0007_alter_barschedule_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekdayAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Disponibilidade por Dia',
                'verbose_name_plural': 'Disponibilidades por Dia',
                'ordering': ['weekday', 'start_time'],
            },
        ),
    ]
