# Generated by Django 5.2.10 on 2026-02-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0009_schoolaccount_schooltransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
