# Generated by Django 5.2.10 on 2026-03-05 18:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0010_user_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bar_app.order')),
            ],
            options={
                'verbose_name': 'Avaliação de Pedido',
                'verbose_name_plural': 'Avaliações de Pedidos',
                'ordering': ['-created_at'],
            },
        ),
    ]
