# Generated by Django 6.0.3 on 2026-03-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0012_favoriteproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.CharField(blank=True, help_text='Ex: Glúten, Lactose, Frutos Secos', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='Data de validade do lote atual', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='loyalty_points',
            field=models.IntegerField(default=0, help_text='Pontos de fidelidade (1€ = 1 ponto)'),
        ),
    ]
