# Generated by Django 5.2.13 on 2026-04-14 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0013_product_allergens_product_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barschedule',
            options={'ordering': ['start_day'], 'verbose_name': 'Horário do Bar', 'verbose_name_plural': 'Horários do Bar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-is_priority', 'scheduled_date', 'scheduled_time', 'created_at'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['product__name'], 'verbose_name': 'Item de Pedido', 'verbose_name_plural': 'Itens de Pedido'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='schooltransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transação da Escola', 'verbose_name_plural': 'Transações da Escola'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Movimento de Stock', 'verbose_name_plural': 'Movimentos de Stock'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transação', 'verbose_name_plural': 'Transações'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Utilizador', 'verbose_name_plural': 'Utilizadores'},
        ),
        migrations.AlterField(
            model_name='schooltransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montante'),
        ),
        migrations.AlterField(
            model_name='schooltransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='schooltransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='schooltransaction',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='schooltransaction',
            name='movement_type',
            field=models.CharField(choices=[('income', 'Entrada'), ('expense', 'Despesa')], max_length=10, verbose_name='Tipo de Movimento'),
        ),
        migrations.AlterField(
            model_name='schooltransaction',
            name='school_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bar_app.schoolaccount', verbose_name='Conta da Escola'),
        ),
    ]
