# Generated by Django 5.2.13 on 2026-04-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0015_alter_barschedule_closing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Cartão Escolar'), ('atm', 'Multibanco')], max_length=10, verbose_name='Método de Pagamento'),
        ),
    ]
