# Generated by Django 6.0.4 on 2026-04-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0017_product_purchase_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='escalao',
            field=models.CharField(choices=[('none', 'Nenhum'), ('A', 'Escalão A'), ('B', 'Escalão B'), ('C', 'Escalão C')], default='none', max_length=10, verbose_name='Escalão ASE'),
        ),
    ]
