# Generated by Django 5.2.14 on 2026-05-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0018_user_escalao'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allergens',
            field=models.CharField(blank=True, default='', help_text='Alérgenos separados por vírgula (ex: Glúten, Lactose)', max_length=255, verbose_name='Alérgenos / Restrições'),
        ),
    ]
