# Generated by Django 5.2.15 on 2026-06-18 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0019_user_allergens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='loyalty_points',
        ),
    ]
