# Generated by Django 5.2.17 on 2026-08-15 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_app', '0020_remove_loyalty_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Levantado em'),
        ),
        migrations.AddField(
            model_name='order',
            name='picked_up_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_up_orders', to=settings.AUTH_USER_MODEL, verbose_name='Levantado por'),
        ),
        migrations.AddField(
            model_name='order',
            name='qr_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Token QR Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='turma',
            field=models.CharField(blank=True, help_text='Turma do utilizador (ex: 12PI)', max_length=10, verbose_name='Turma'),
        ),
    ]
